# generated by datamodel-codegen:
#   filename:  .generation.json

from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict


class Inbox(TypedDict):
    id: str
    local_part: str
    address: str
    name: str | None
    sender_name: str | None
    created_at: str


class InboxAllowance(TypedDict):
    allowance: int
    used: int
    remaining: int
    unit: Literal['inbox_slots']


class Error1(TypedDict):
    code: str
    message: str


class Error(TypedDict):
    error: Error1


class CreatedInbox(TypedDict):
    id: str
    local_part: str
    address: str
    name: str | None
    sender_name: str | None
    created_at: str
    replayed: NotRequired[bool]
    idempotency_expires_at: NotRequired[str]


class Details(TypedDict):
    allowance: InboxAllowance
    increase_request: str
    policy_url: str


class Error2(TypedDict):
    code: str
    message: str
    details: NotRequired[Details]


class InboxError(TypedDict):
    error: Error2


class CreateInbox(TypedDict):
    local_part: str
    name: NotRequired[str | None]
    sender_name: NotRequired[str | None]
    idempotency_key: NotRequired[str]


class UpdateInbox(TypedDict):
    name: NotRequired[str | None]
    sender_name: NotRequired[str | None]


class Deleted(TypedDict):
    id: str
    status: Literal['deletion_pending']
    message: str


class Policy(TypedDict):
    inbox_id: str
    enabled: bool
    addresses: list[str]
    domains: list[str]
    revision: int


Label: TypeAlias = str


class ReceivedSummary2(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    envelope_from: str
    envelope_to: str
    subject: str | None
    received_at: str
    processing_status: Literal['pending', 'processing', 'failed']
    labels: list[str]
    preview: None


class Preview(TypedDict):
    text: str
    truncated: bool
    source: Literal['reply_text', 'text', 'html']


class ParsedAddress1(TypedDict):
    name: str
    address: str


class GroupItem(TypedDict):
    name: str
    address: str


class ParsedAddress2(TypedDict):
    name: str
    group: list[GroupItem]


ParsedAddress: TypeAlias = ParsedAddress1 | ParsedAddress2


class ReceivedDetail2(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    envelope_from: str
    envelope_to: str
    subject: str | None
    received_at: str
    processing_status: Literal['pending', 'processing', 'failed']
    labels: list[str]
    message_id: str | None
    raw_size: int
    processed_at: str | None


class ReceivedAttachment(TypedDict):
    id: str
    filename: str | None
    size: int
    mime_type: str
    disposition: str | None
    content_id: str | None
    related: bool


class LabelResult(TypedDict):
    id: str
    labels: list[str]


class LabelChange(TypedDict):
    add_labels: NotRequired[list[Label]]
    remove_labels: NotRequired[list[Label]]


Headers = TypedDict(
    'Headers',
    {
        'In-Reply-To': str,
        'References': str,
    },
)


class Mailbox(TypedDict):
    address: str
    name: NotRequired[str]


class StoredAttachment(TypedDict):
    filename: str
    type: str
    content: str
    disposition: Literal['attachment', 'inline']
    contentId: NotRequired[str]


MessageId: TypeAlias = str


class BulkLabelChange(TypedDict):
    message_ids: list[MessageId]
    add_labels: NotRequired[list[Label]]
    remove_labels: NotRequired[list[Label]]


class Label1(TypedDict):
    name: str
    received_count: int
    sent_count: int


class LabelList(TypedDict):
    labels: list[Label1]
    next_cursor: str | None


class SentMetadata(TypedDict):
    id: str
    inbox_id: str
    created_at: str
    recipient_count: int
    status: Literal['accepted', 'rejected', 'unknown']
    provider_message_id: str | None
    error_code: str | None
    thread_id: str | None
    in_reply_to: str | None
    labels: list[str]


class Error3(TypedDict):
    code: Literal['outbound_limit_reached']
    message: str


class Quota(TypedDict):
    allowance: int
    used: int
    remaining: int
    next_capacity_at: str | None
    next_capacity_amount: int
    window_hours: Literal[24]
    unit: Literal['recipient_deliveries']
    increase_request: str
    policy_url: str


class AttachmentInput(TypedDict):
    filename: str
    type: str
    content: str


class SentSummary(TypedDict):
    id: str
    inbox_id: str
    created_at: str
    recipient_count: int
    status: Literal['accepted', 'rejected', 'unknown']
    provider_message_id: str | None
    error_code: str | None
    thread_id: str | None
    in_reply_to: str | None
    labels: list[str]
    preview: Preview | None


class ReplyInput(TypedDict):
    message_id: str
    text: str
    html: NotRequired[str]
    attachments: NotRequired[list[AttachmentInput] | None]
    labels: NotRequired[list[Label]]
    idempotency_key: NotRequired[str]


class ForwardInput(TypedDict):
    message_id: str
    to: list[Mailbox]
    cc: NotRequired[list[Mailbox]]
    bcc: NotRequired[list[Mailbox]]
    note: NotRequired[str]
    include_attachments: NotRequired[bool]
    labels: NotRequired[list[Label]]
    idempotency_key: NotRequired[str]


class CreatedDraft(TypedDict):
    id: str
    inbox_id: str
    state: Literal['draft', 'submitted']
    subject: str
    created_at: str
    updated_at: str
    sent_message_id: str | None
    replayed: NotRequired[bool]
    idempotency_expires_at: NotRequired[str]


class Source(TypedDict):
    action: Literal['reply', 'reply-all']
    message_id: str


class Source1(TypedDict):
    action: Literal['forward']
    message_id: str
    include_attachments: NotRequired[bool]


class CreateDraft(TypedDict):
    to: NotRequired[list[Mailbox]]
    cc: NotRequired[list[Mailbox]]
    bcc: NotRequired[list[Mailbox]]
    subject: NotRequired[str]
    text: NotRequired[str]
    html: NotRequired[str | None]
    attachments: NotRequired[list[AttachmentInput] | None]
    in_reply_to: NotRequired[str | None]
    labels: NotRequired[list[Label]]
    idempotency_key: NotRequired[str]
    source: NotRequired[Source | Source1]


class DraftMetadata(TypedDict):
    id: str
    inbox_id: str
    state: Literal['draft', 'submitted']
    subject: str
    created_at: str
    updated_at: str
    sent_message_id: str | None


class DraftContent(TypedDict):
    to: list[Mailbox]
    cc: list[Mailbox]
    bcc: list[Mailbox]
    subject: str
    text: str
    html: NotRequired[str]
    in_reply_to: NotRequired[str]
    labels: NotRequired[list[str]]
    attachments: list[StoredAttachment]


class UpdateDraft(TypedDict):
    to: NotRequired[list[Mailbox]]
    cc: NotRequired[list[Mailbox]]
    bcc: NotRequired[list[Mailbox]]
    subject: NotRequired[str]
    text: NotRequired[str]
    html: NotRequired[str | None]
    attachments: NotRequired[list[AttachmentInput] | None]
    in_reply_to: NotRequired[str | None]
    labels: NotRequired[list[Label]]


class DeletedDraft(TypedDict):
    id: str
    status: Literal['deletion_pending']
    message: str


class SendDraft(TypedDict):
    idempotency_key: NotRequired[str]


class ThreadLatestMessage1(TypedDict):
    id: str
    direction: Literal['received']
    counterpart: ParsedAddress | None
    preview: Preview | None


class ThreadLatestMessage2(TypedDict):
    id: str
    direction: Literal['sent']
    counterpart: Mailbox | None
    preview: Preview | None


ThreadLatestMessage: TypeAlias = ThreadLatestMessage1 | ThreadLatestMessage2


class ThreadReceivedDetail2(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    envelope_from: str
    envelope_to: str
    subject: str | None
    received_at: str
    processing_status: Literal['pending', 'processing', 'failed']
    labels: list[str]
    message_id: str | None
    raw_size: int
    processed_at: str | None


class ThreadReceivedDetail3(TypedDict):
    direction: Literal['received']
    timestamp: str


class ThreadReceivedDetail5(ThreadReceivedDetail2, ThreadReceivedDetail3):
    pass


class Attachment(TypedDict):
    id: str
    filename: str
    mime_type: str
    size: int


Submission1 = TypedDict(
    'Submission1',
    {
        'to': list[Mailbox | str],
        'cc': list[Mailbox | str],
        'bcc': list[Mailbox | str],
        'subject': str,
        'text': str,
        'html': NotRequired[str],
        'attachments': list[Attachment],
        'from': Mailbox | str,
        'headers': NotRequired[Headers],
    },
)


class ThreadSentDetail(TypedDict):
    id: str
    inbox_id: str
    created_at: str
    recipient_count: int
    status: Literal['accepted', 'rejected', 'unknown']
    provider_message_id: str | None
    error_code: str | None
    thread_id: str | None
    in_reply_to: str | None
    labels: list[str]
    direction: Literal['sent']
    timestamp: str
    reply_text: str | None
    submission: Submission1


class ThreadLabelResult(TypedDict):
    id: str
    inbox_id: str
    message_count: int
    received_count: int
    sent_count: int
    add_labels: list[str]
    remove_labels: list[str]


class DeletedThread(TypedDict):
    id: str
    inbox_id: str
    message_count: int
    received_count: int
    sent_count: int
    status: Literal['deletion_pending']
    message: str


TrashEntry1 = TypedDict(
    'TrashEntry1',
    {
        'id': str,
        'kind': Literal['received'],
        'inbox_id': str,
        'subject': str | None,
        'from': ParsedAddress | None,
        'envelope_from': str,
        'deleted_at': str,
        'restorable_until': str,
    },
)


class TrashEntry2(TypedDict):
    id: str
    kind: Literal['sent']
    inbox_id: str
    subject: str | None
    to: list[Mailbox]
    deleted_at: str
    restorable_until: str


TrashEntry: TypeAlias = TrashEntry1 | TrashEntry2


class Restored(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    status: Literal['restored', 'already_live']
    message: str


class CreateInboxParams(TypedDict):
    body: CreateInbox


class CreateInboxResult1(TypedDict):
    id: str
    local_part: str
    address: str
    name: str | None
    sender_name: str | None
    created_at: str
    replayed: Literal[True]
    idempotency_expires_at: str


class CreateInboxResult2(TypedDict):
    id: str
    local_part: str
    address: str
    name: str | None
    sender_name: str | None
    created_at: str
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


CreateInboxResult: TypeAlias = CreateInboxResult1 | CreateInboxResult2


class GetInboxParams(TypedDict):
    inbox_id: str


GetInboxResult: TypeAlias = Inbox


class UpdateInboxParams(TypedDict):
    inbox_id: str
    body: UpdateInbox


UpdateInboxResult: TypeAlias = Inbox


class DeleteInboxParams(TypedDict):
    inbox_id: str


DeleteInboxResult: TypeAlias = Deleted


class GetSendingPolicyParams(TypedDict):
    inbox_id: str


GetSendingPolicyResult: TypeAlias = Policy


class GetReceivingPolicyParams(TypedDict):
    inbox_id: str


GetReceivingPolicyResult: TypeAlias = Policy


ListMessagesParams = TypedDict(
    'ListMessagesParams',
    {
        'inbox_id': str,
        'limit': NotRequired[int],
        'cursor': NotRequired[str],
        'query': NotRequired[str],
        'from': NotRequired[str],
        'recipient': NotRequired[str],
        'subject': NotRequired[str],
        'after': NotRequired[str],
        'before': NotRequired[str],
        'labels_all': NotRequired[list[Label]],
        'labels_any': NotRequired[list[Label]],
        'labels_none': NotRequired[list[Label]],
        'order': NotRequired[Literal['newest', 'oldest', 'relevance']],
    },
)


CountMessagesParams = TypedDict(
    'CountMessagesParams',
    {
        'inbox_id': str,
        'query': NotRequired[str],
        'from': NotRequired[str],
        'recipient': NotRequired[str],
        'subject': NotRequired[str],
        'after': NotRequired[str],
        'before': NotRequired[str],
        'labels_all': NotRequired[list[Label]],
        'labels_any': NotRequired[list[Label]],
        'labels_none': NotRequired[list[Label]],
    },
)


class CountMessagesResult(TypedDict):
    count: int


class GetMessageParams(TypedDict):
    message_id: str


class DeleteMessageParams(TypedDict):
    message_id: str


DeleteMessageResult: TypeAlias = Deleted


class UpdateMessageLabelsParams(TypedDict):
    message_id: str
    body: LabelChange


UpdateMessageLabelsResult: TypeAlias = LabelResult


class DownloadRawMessageParams(TypedDict):
    message_id: str


class DownloadAttachmentParams(TypedDict):
    message_id: str
    attachment_id: str


class DeleteSentMessageParams(TypedDict):
    message_id: str


DeleteSentMessageResult: TypeAlias = Deleted


class UpdateSentMessageLabelsParams(TypedDict):
    message_id: str
    body: LabelChange


UpdateSentMessageLabelsResult: TypeAlias = LabelResult


class GetSentMessageParams(TypedDict):
    message_id: str


class BulkUpdateMessageLabelsParams(TypedDict):
    body: BulkLabelChange


class BulkUpdateMessageLabelsResult(TypedDict):
    messages: list[LabelResult]


class BulkUpdateSentLabelsParams(TypedDict):
    body: BulkLabelChange


class BulkUpdateSentLabelsResult(TypedDict):
    messages: list[LabelResult]


class ListLabelsParams(TypedDict):
    inbox_id: str
    limit: NotRequired[int]
    cursor: NotRequired[str]
    prefix: NotRequired[str]


ListLabelsResult: TypeAlias = LabelList


class ListLabelsItem(TypedDict):
    name: str
    received_count: int
    sent_count: int


class SendMessageResult1(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: Literal[True]
    idempotency_expires_at: str


class SendMessageResult2(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


SendMessageResult: TypeAlias = SendMessageResult1 | SendMessageResult2


ListSentMessagesParams = TypedDict(
    'ListSentMessagesParams',
    {
        'inbox_id': str,
        'limit': NotRequired[int],
        'cursor': NotRequired[str],
        'query': NotRequired[str],
        'from': NotRequired[str],
        'recipient': NotRequired[str],
        'subject': NotRequired[str],
        'after': NotRequired[str],
        'before': NotRequired[str],
        'labels_all': NotRequired[list[Label]],
        'labels_any': NotRequired[list[Label]],
        'labels_none': NotRequired[list[Label]],
        'order': NotRequired[Literal['newest', 'oldest', 'relevance']],
    },
)


class ListSentMessagesResult(TypedDict):
    messages: list[SentSummary]
    next_cursor: str | None


ListSentMessagesItem: TypeAlias = SentSummary


class ReplyMessageParams(TypedDict):
    inbox_id: str
    body: ReplyInput


class ReplyMessageResult1(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: Literal[True]
    idempotency_expires_at: str


class ReplyMessageResult2(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


ReplyMessageResult: TypeAlias = ReplyMessageResult1 | ReplyMessageResult2


class ReplyAllMessageParams(TypedDict):
    inbox_id: str
    body: ReplyInput


class ReplyAllMessageResult1(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: Literal[True]
    idempotency_expires_at: str


class ReplyAllMessageResult2(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


ReplyAllMessageResult: TypeAlias = ReplyAllMessageResult1 | ReplyAllMessageResult2


class ForwardMessageParams(TypedDict):
    inbox_id: str
    body: ForwardInput


class ForwardMessageResult1(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: Literal[True]
    idempotency_expires_at: str


class ForwardMessageResult2(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


ForwardMessageResult: TypeAlias = ForwardMessageResult1 | ForwardMessageResult2


GetOutboundQuotaResult: TypeAlias = Quota


class CreateDraftParams(TypedDict):
    inbox_id: str
    body: CreateDraft


class CreateDraftResult1(TypedDict):
    id: str
    inbox_id: str
    state: Literal['draft', 'submitted']
    subject: str
    created_at: str
    updated_at: str
    sent_message_id: str | None
    replayed: Literal[True]
    idempotency_expires_at: str


class CreateDraftResult2(TypedDict):
    id: str
    inbox_id: str
    state: Literal['draft', 'submitted']
    subject: str
    created_at: str
    updated_at: str
    sent_message_id: str | None
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


CreateDraftResult: TypeAlias = CreateDraftResult1 | CreateDraftResult2


class ListDraftsParams(TypedDict):
    inbox_id: str
    limit: NotRequired[int]
    cursor: NotRequired[str]
    state: NotRequired[Literal['draft', 'submitted', 'all']]


class ListDraftsResult(TypedDict):
    drafts: list[DraftMetadata]
    next_cursor: str | None


ListDraftsItem: TypeAlias = DraftMetadata


class GetDraftParams(TypedDict):
    draft_id: str


class UpdateDraftParams(TypedDict):
    draft_id: str
    body: UpdateDraft


UpdateDraftResult: TypeAlias = DraftMetadata


class DeleteDraftParams(TypedDict):
    draft_id: str


DeleteDraftResult: TypeAlias = DeletedDraft


class SendDraftParams(TypedDict):
    draft_id: str
    body: SendDraft


class SendDraftResult1(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: Literal[True]
    idempotency_expires_at: NotRequired[str]


class SendDraftResult2(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[Literal[False]]
    idempotency_expires_at: NotRequired[str]


SendDraftResult: TypeAlias = SendDraftResult1 | SendDraftResult2


ListThreadsParams = TypedDict(
    'ListThreadsParams',
    {
        'inbox_id': str,
        'limit': NotRequired[int],
        'cursor': NotRequired[str],
        'query': NotRequired[str],
        'from': NotRequired[str],
        'recipient': NotRequired[str],
        'subject': NotRequired[str],
        'after': NotRequired[str],
        'before': NotRequired[str],
        'labels_all': NotRequired[list[Label]],
        'labels_any': NotRequired[list[Label]],
        'labels_none': NotRequired[list[Label]],
        'order': NotRequired[Literal['newest', 'oldest', 'relevance']],
    },
)


class GetThreadParams(TypedDict):
    thread_id: str
    limit: NotRequired[int]
    cursor: NotRequired[str]


class UpdateThreadLabelsParams(TypedDict):
    thread_id: str
    body: LabelChange


UpdateThreadLabelsResult: TypeAlias = ThreadLabelResult


class DeleteThreadParams(TypedDict):
    thread_id: str


DeleteThreadResult: TypeAlias = DeletedThread


class ListTrashParams(TypedDict):
    inbox_id: str
    limit: NotRequired[int]
    cursor: NotRequired[str]


class ListTrashResult(TypedDict):
    messages: list[TrashEntry]
    next_cursor: str | None


ListTrashItem: TypeAlias = TrashEntry


class RestoreMessageParams(TypedDict):
    message_id: str


RestoreMessageResult: TypeAlias = Restored


class RestoreSentMessageParams(TypedDict):
    message_id: str


RestoreSentMessageResult: TypeAlias = Restored


class InboxList(TypedDict):
    inboxes: list[Inbox]
    inbox_limit: int
    inbox_allowance: InboxAllowance


ReceivedSummary1 = TypedDict(
    'ReceivedSummary1',
    {
        'id': str,
        'inbox_id': str,
        'thread_id': str | None,
        'envelope_from': str,
        'envelope_to': str,
        'subject': str | None,
        'received_at': str,
        'processing_status': Literal['ready'],
        'labels': list[str],
        'preview': Preview | None,
        'from': ParsedAddress | None,
    },
)


ReceivedSummary: TypeAlias = ReceivedSummary1 | ReceivedSummary2


ReceivedContent = TypedDict(
    'ReceivedContent',
    {
        'from': ParsedAddress | None,
        'sender': ParsedAddress | None,
        'reply_to': list[ParsedAddress],
        'to': list[ParsedAddress],
        'cc': list[ParsedAddress],
        'bcc': list[ParsedAddress],
        'subject': str | None,
        'message_id': str | None,
        'in_reply_to': str | None,
        'references': str | None,
        'date': str | None,
        'reply_text': str | None,
        'text': str | None,
        'html': str | None,
        'attachments': list[ReceivedAttachment],
    },
)


Submission = TypedDict(
    'Submission',
    {
        'to': list[Mailbox | str],
        'cc': list[Mailbox | str],
        'bcc': list[Mailbox | str],
        'subject': str,
        'text': str,
        'html': NotRequired[str],
        'attachments': list[StoredAttachment],
        'from': Mailbox | str,
        'headers': NotRequired[Headers],
    },
)


class SendReceipt(TypedDict):
    limited: Literal[False]
    message: SentMetadata
    outcome_persisted: bool
    replayed: NotRequired[bool]
    idempotency_expires_at: NotRequired[str]


class QuotaError(TypedDict):
    error: Error3
    quota: Quota
    requested_recipients: int
    reason: Literal['temporary_exhaustion', 'message_exceeds_allowance']
    sufficient_capacity_at: str | None
    guidance: str


class SendInput(TypedDict):
    to: list[Mailbox]
    cc: NotRequired[list[Mailbox]]
    bcc: NotRequired[list[Mailbox]]
    subject: str
    text: str
    html: NotRequired[str]
    attachments: NotRequired[list[AttachmentInput] | None]
    in_reply_to: NotRequired[str]
    labels: NotRequired[list[Label]]
    idempotency_key: NotRequired[str]


DraftDetail = TypedDict(
    'DraftDetail',
    {
        'id': str,
        'inbox_id': str,
        'state': Literal['draft', 'submitted'],
        'subject': str,
        'created_at': str,
        'updated_at': str,
        'sent_message_id': str | None,
        'from': Mailbox,
        'content': DraftContent,
    },
)


class ThreadSummary(TypedDict):
    id: str
    inbox_id: str
    subject: str | None
    last_activity_at: str
    message_count: int
    received_count: int
    accepted_count: int
    rejected_count: int
    unknown_count: int
    latest_message: ThreadLatestMessage
    matching_message_ids: NotRequired[list[str]]
    matching_message_count: NotRequired[int]


class ThreadReceivedDetail1(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    envelope_from: str
    envelope_to: str
    subject: str | None
    received_at: str
    processing_status: Literal['ready']
    labels: list[str]
    message_id: str | None
    raw_size: int
    processed_at: str | None
    content: ReceivedContent


class ThreadReceivedDetail4(ThreadReceivedDetail1, ThreadReceivedDetail3):
    pass


ThreadReceivedDetail: TypeAlias = ThreadReceivedDetail4 | ThreadReceivedDetail5


ListInboxesResult: TypeAlias = InboxList


class ListMessagesResult(TypedDict):
    messages: list[ReceivedSummary]
    next_cursor: str | None


ListMessagesItem: TypeAlias = ReceivedSummary


class SendMessageParams(TypedDict):
    inbox_id: str
    body: SendInput


GetDraftResult: TypeAlias = DraftDetail


class ListThreadsResult(TypedDict):
    threads: list[ThreadSummary]
    next_cursor: str | None


ListThreadsItem: TypeAlias = ThreadSummary


GetThreadItem: TypeAlias = ThreadReceivedDetail | ThreadSentDetail


class ReceivedDetail1(TypedDict):
    id: str
    inbox_id: str
    thread_id: str | None
    envelope_from: str
    envelope_to: str
    subject: str | None
    received_at: str
    processing_status: Literal['ready']
    labels: list[str]
    message_id: str | None
    raw_size: int
    processed_at: str | None
    content: ReceivedContent


ReceivedDetail: TypeAlias = ReceivedDetail1 | ReceivedDetail2


class SentDetail(TypedDict):
    id: str
    inbox_id: str
    created_at: str
    recipient_count: int
    status: Literal['accepted', 'rejected', 'unknown']
    provider_message_id: str | None
    error_code: str | None
    thread_id: str | None
    in_reply_to: str | None
    labels: list[str]
    reply_text: str | None
    submission: Submission


class ThreadDetail(TypedDict):
    id: str
    inbox_id: str
    subject: str | None
    last_activity_at: str
    message_count: int
    received_count: int
    accepted_count: int
    rejected_count: int
    unknown_count: int
    messages: list[ThreadReceivedDetail | ThreadSentDetail]
    next_cursor: str | None


GetMessageResult: TypeAlias = ReceivedDetail


GetSentMessageResult: TypeAlias = SentDetail


GetThreadResult: TypeAlias = ThreadDetail
